#pragma once

#define JIXIA_TASK_SYSCALL_YIELD 0
#define JIXIA_TASK_SYSCALL_CREATE 1
#define JIXIA_TASK_SYSCALL_END 2
#define JIXIA_TASK_SYSCALL_WAIT 3
#define JIXIA_TASK_SYSCALL_DETACH 4
#define JIXIA_TASK_SYSCALL_COUNT 5
